/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mugiha01' at '12/5/17 9:57 PM' with Gradle 2.14.1
 *
 * @author mugiha01, @date 12/5/17 9:57 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
